


import { Product, Order, OrderSource, OrderStatus, Language, PaymentStatus, PaymentMethod, Supplier } from './types';

export const APP_VERSION = "2.4";
export const APP_DATE = "03 December 2025";

export const MOCK_SUPPLIERS: Supplier[] = [
  { id: 1, name: "PetFood Ukraine LLC", contactPerson: "Sergey", phone: "+380501112233" },
  { id: 2, name: "ZooPostach Ltd", contactPerson: "Olga", phone: "+380672223344" },
  { id: 3, name: "KormTech Import", contactPerson: "Andriy", phone: "+380933334455" }
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    sku: "DOG-FOOD-001",
    barcode: "482000000001",
    name_ru: "Корм для собак Премиум 10кг",
    name_uk: "Корм для собак Преміум 10кг",
    description_ru: "Сбалансированный сухой корм для взрослых собак всех пород.",
    description_uk: "Збалансований сухий корм для дорослих собак всіх порід.",
    price: 1200,
    purchasePrice: 800,
    promotional_price: 1100,
    stock: 45,
    category: "Food",
    imageUrl: "https://picsum.photos/200/200?random=1"
  },
  {
    id: 2,
    sku: "CAT-TOY-055",
    barcode: "482000000002",
    name_ru: "Игрушка для котов 'Мышка'",
    name_uk: "Іграшка для котів 'Мишка'",
    description_ru: "Интерактивная игрушка с кошачьей мятой.",
    description_uk: "Інтерактивна іграшка з котячою м'ятою.",
    price: 150,
    purchasePrice: 60,
    stock: 120,
    category: "Toys",
    imageUrl: "https://picsum.photos/200/200?random=2"
  },
  {
    id: 3,
    sku: "DOG-LEASH-PRO",
    barcode: "482000000003",
    name_ru: "Поводок-рулетка 5м",
    name_uk: "Повідець-рулетка 5м",
    description_ru: "Прочный поводок для собак до 20кг.",
    description_uk: "Міцний повідець для собак до 20кг.",
    price: 450,
    purchasePrice: 250,
    stock: 12,
    category: "Accessories",
    imageUrl: "https://picsum.photos/200/200?random=3"
  }
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 101,
    orderNumber: "ORD-20231203-001",
    source: OrderSource.ROZETKA,
    sourceOrderNumber: "ROZETKA_778899",
    customerName: "Ivan Petrenko",
    customerPhone: "+380501234567",
    deliveryCity: "Kyiv",
    deliveryService: "nova_poshta",
    deliveryWarehouse: "Branch #55",
    shippingCost: 70,
    total: 1350,
    status: OrderStatus.NEW,
    paymentStatus: PaymentStatus.NOT_PAID,
    paymentMethod: PaymentMethod.COD,
    date: "2025-12-03T10:30:00",
    items: [{ productId: 1, productName: "Корм для собак Премиум 10кг", quantity: 1, price: 1100, discount: 0 }, { productId: 2, productName: "Игрушка 'Мышка'", quantity: 1, price: 250, discount: 0 }]
  },
  {
    id: 102,
    orderNumber: "ORD-20231203-002",
    source: OrderSource.MY_DOG,
    customerName: "Maria Kovalenko",
    customerPhone: "+380679876543",
    deliveryCity: "Lviv",
    deliveryService: "rozetka_delivery",
    deliveryWarehouse: "Postomat 2021",
    ttn: "20450567891234",
    total: 450,
    status: OrderStatus.SHIPPED,
    paymentStatus: PaymentStatus.PAID,
    paymentMethod: PaymentMethod.CARD,
    date: "2025-12-02T14:15:00",
    items: [{ productId: 3, productName: "Поводок-рулетка 5м", quantity: 1, price: 450, discount: 0 }]
  },
  {
    id: 103,
    orderNumber: "ORD-20231203-003",
    source: OrderSource.PROM,
    sourceOrderNumber: "PROM_112233",
    customerName: "Oleg Bondar",
    customerPhone: "+380935554433",
    deliveryCity: "Odessa",
    deliveryService: "nova_poshta",
    deliveryWarehouse: "Branch #10",
    total: 2400,
    status: OrderStatus.PROCESSING,
    paymentStatus: PaymentStatus.PARTIALLY_PAID,
    paymentMethod: PaymentMethod.IBAN,
    date: "2025-12-03T09:00:00",
    items: [{ productId: 1, productName: "Корм для собак Премиум 10кг", quantity: 2, price: 1200, discount: 0 }]
  }
];

export const UI_TEXT = {
  [Language.RU]: {
    dashboard: "Дашборд",
    products: "Товары",
    warehouse: "Склад",
    orders: "Заказы",
    analytics: "Аналитика",
    settings: "Настройки",
    addProduct: "Добавить товар",
    edit: "Редактировать",
    save: "Сохранить",
    cancel: "Отмена",
    back: "Назад",
    generateAi: "Сгенерировать AI",
    totalSales: "Общие продажи",
    totalOrders: "Всего заказов",
    stock: "Остаток",
    price: "Цена",
    source: "Источник",
    sourceId: "№ источника",
    status: "Статус",
    search: "Поиск (SKU, Штрихкод, Имя)...",
    searchPlaceholder: "Поиск товара...",
    loading: "Загрузка...",
    generateTTN: "Сформировать ТТН",
    printInvoice: "Печать накладной",
    shippingDetails: "Доставка",
    customer: "Клиент",
    items: "Товары",
    aiPackaging: "AI Помощник упаковки",
    address: "Адрес",
    ttn: "ТТН",
    phone: "Телефон",
    city: "Город",
    deliveryService: "Служба доставки",
    warehouseAddress: "Отделение/Адрес",
    qty: "Кол-во",
    discount: "Скидка",
    total: "Итого",
    addItem: "Добавить товар",
    selectProduct: "Выберите товар",
    add: "Добавить",
    delete: "Удалить",
    purchasePrice: "Закупка",
    margin: "Маржа %",
    barcode: "Штрихкод",
    category: "Категория",
    allCategories: "Все категории",
    integrations: "Интеграции API",
    apiKeys: "API Ключи",
    import: "Импорт",
    importDesc: "Загрузите файл Excel или XML",
    selectFile: "Выбрать файл",
    mapColumns: "Настройка полей",
    mapDesc: "Сопоставьте колонки файла с полями системы",
    fileColumn: "Колонка в файле",
    systemField: "Поле в системе",
    startImport: "Начать импорт",
    receiving: "Приемка товара",
    receiveStock: "Принять",
    currentStock: "Текущий остаток",
    addStock: "Добавить кол-во",
    newPurchasePrice: "Цена закупки (новая)",
    shippingCost: "Затраты на доставку",
    profit: "Прибыль",
    searchForOrder: "Введите название или артикул...",
    sku: "Артикул",
    payment: "Оплата",
    paymentStatus: "Статус оплаты",
    paymentMethod: "Метод оплаты",
    bankCommission: "Комиссия банка (%)",
    fetchFromTTN: "Обновить по ТТН",
    supplier: "Поставщик",
    extraCosts: "Доп. расходы (Доставка и др.)",
    paymentDate: "Дата оплаты",
    createReceipt: "Создать поступление",
    selectSupplier: "Выберите поставщика",
    financials: "Финансы",
    netProfit: "Чистая прибыль"
  },
  [Language.UK]: {
    dashboard: "Дашборд",
    products: "Товари",
    warehouse: "Склад",
    orders: "Замовлення",
    analytics: "Аналітика",
    settings: "Налаштування",
    addProduct: "Додати товар",
    edit: "Редагувати",
    save: "Зберегти",
    cancel: "Скасувати",
    back: "Назад",
    generateAi: "Згенерувати AI",
    totalSales: "Загальні продажі",
    totalOrders: "Всього замовлень",
    stock: "Залишок",
    price: "Ціна",
    source: "Джерело",
    sourceId: "№ джерела",
    status: "Статус",
    search: "Пошук (SKU, Штрихкод, Назва)...",
    searchPlaceholder: "Пошук товару...",
    loading: "Завантаження...",
    generateTTN: "Сформувати ТТН",
    printInvoice: "Друк накладної",
    shippingDetails: "Доставка",
    customer: "Клієнт",
    items: "Товари",
    aiPackaging: "AI Помічник пакування",
    address: "Адреса",
    ttn: "ТТН",
    phone: "Телефон",
    city: "Місто",
    deliveryService: "Служба доставки",
    warehouseAddress: "Відділення/Адреса",
    qty: "Кіл-сть",
    discount: "Знижка",
    total: "Разом",
    addItem: "Додати товар",
    selectProduct: "Оберіть товар",
    add: "Додати",
    delete: "Видалити",
    purchasePrice: "Закупівля",
    margin: "Маржа %",
    barcode: "Штрихкод",
    category: "Категорія",
    allCategories: "Всі категорії",
    integrations: "Інтеграції API",
    apiKeys: "API Ключі",
    import: "Імпорт",
    importDesc: "Завантажте файл Excel або XML",
    selectFile: "Обрати файл",
    mapColumns: "Налаштування полів",
    mapDesc: "Зіставте колонки файлу з полями системи",
    fileColumn: "Колонка у файлі",
    systemField: "Поле в системі",
    startImport: "Почати імпорт",
    receiving: "Приймання товару",
    receiveStock: "Прийняти",
    currentStock: "Поточний залишок",
    addStock: "Додати кількість",
    newPurchasePrice: "Ціна закупівлі (нова)",
    shippingCost: "Витрати на доставку",
    profit: "Прибуток",
    searchForOrder: "Введіть назву або артикул...",
    sku: "Артикул",
    payment: "Оплата",
    paymentStatus: "Статус оплати",
    paymentMethod: "Метод оплати",
    bankCommission: "Комісія банку (%)",
    fetchFromTTN: "Оновити по ТТН",
    supplier: "Постачальник",
    extraCosts: "Дод. витрати (Доставка та ін.)",
    paymentDate: "Дата оплати",
    createReceipt: "Створити надходження",
    selectSupplier: "Оберіть постачальника",
    financials: "Фінанси",
    netProfit: "Чистий прибуток"
  }
};
